# Generated by Django 3.2 on 2021-05-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepit',
            name='query_string',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
